name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
      - LICENSE
      - README.md
  workflow_dispatch: null
  pull_request: null
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gh.outputs.version }}
      release: ${{ steps.gh.outputs.release }}
      sha: ${{ steps.gh.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: GH
        id: gh
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: >
          echo "version=$(cat Makefile | grep "PKG_VERSION :=" | sed 's/PKG_VERSION
          := //')" >> $GITHUB_OUTPUT

          echo "release=$(cat Makefile | grep "PKG_RELEASE :=" | sed 's/PKG_RELEASE := //')" >> $GITHUB_OUTPUT


          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            GITHUB_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)
          fi

          echo "sha=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT

          cat $GITHUB_OUTPUT
  build-openwrt:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 25.12.2
        include:
          - branch: 25.12.2
            package_extension: apk
        arch:
          - ramips-mt7620
          - ramips-mt7621
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: openwrt
      - name: Prepare build
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          RELEASE: ${{ needs.prepare.outputs.release }}
          SHA: ${{ needs.prepare.outputs.sha }}
        run: >
          sed -i
          "s/PKG_REV:=.*$/PKG_REV:=$SHA/;s/PKG_VERSION:=.*$/PKG_VERSION:=$VERSION/;s/PKG_RELEASE:=.*$/PKG_RELEASE:=$RELEASE/;"
          youtubeUnblock/Makefile
      - name: Initilalize SDK
        id: init_sdk
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          RELEASE: ${{ needs.prepare.outputs.release }}
          SHA: ${{ needs.prepare.outputs.sha }}
        working-directory: /builder
        run: |
          HOME=/builder ./setup.sh
      - name: Build packages
        id: build
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          RELEASE: ${{ needs.prepare.outputs.release }}
          SHA: ${{ needs.prepare.outputs.sha }}
        working-directory: /builder
        run: >
          echo "src-link youtubeUnblock $GITHUB_WORKSPACE" >> feeds.conf

          cat feeds.conf

          ./scripts/feeds update youtubeUnblock

          ./scripts/feeds install -a -p youtubeUnblock

          make defconfig

          make package/youtubeUnblock/compile V=s

          mv $(find ./bin -type f -name "youtubeUnblock*.${{ matrix.package_extension }}") ./youtubeUnblock-$VERSION-$RELEASE-$SHA-${{ matrix.arch }}-${{ matrix.branch }}.${{ matrix.package_extension }}
      - name: Upload packages
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: youtubeUnblock-${{ matrix.branch }}-${{ matrix.arch }}
          path: /builder/youtubeUnblock*.${{ matrix.package_extension }}
          if-no-files-found: error
  build-openwrt-luci:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 25.12.2
        arch:
          - x86_64
        include:
          - branch: 25.12.2
            package_extension: apk
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: openwrt
      - name: Initilalize SDK
        id: init_sdk
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          RELEASE: ${{ needs.prepare.outputs.release }}
          SHA: ${{ needs.prepare.outputs.sha }}
        working-directory: /builder
        run: |
          HOME=/builder ./setup.sh
      - name: Build packages
        id: build
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          RELEASE: ${{ needs.prepare.outputs.release }}
          SHA: ${{ needs.prepare.outputs.sha }}
        working-directory: /builder
        run: >
          echo "src-link youtubeUnblock $GITHUB_WORKSPACE" >> feeds.conf

          cat feeds.conf

          ./scripts/feeds update youtubeUnblock

          ./scripts/feeds install -a -p youtubeUnblock

          make defconfig

          make package/luci-app-youtubeUnblock/compile V=s

          mv $(find ./bin -type f -name 'luci-app-youtubeUnblock*.${{ matrix.package_extension }}') ./luci-app-youtubeUnblock-$VERSION-$RELEASE-$SHA.${{ matrix.package_extension }}
      - name: Upload packages
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-youtubeUnblock-${{ matrix.branch }}
          path: /builder/luci-app-youtubeUnblock*.${{ matrix.package_extension }}
          if-no-files-found: error
